---
- hosts: all
  become: yes
  tasks:
  - name: installing java
    get_url:
     url: http://download.oracle.com/otn-pub/java/jdk/8u141-b15/336fa29ff2bb4ef291e347e091f7f4a7/jdk-8u141-linux-x64.rpm
     dest: /home/ansible
  - name:  java
    command: cd /home/ansible 
  - name: install java
    command: yum localinstall jdk-8u141-linux-x64.rpm
