---
- hosts: all
  become: yes
  tasks:
  - name: install epel
    yum:
      name: epel-release
      state: installed
  - name: installing nginx   
    yum:
      name: nginx
      state: installed
  - name: service nginx start    
    service:
      name: nginx
      state: started
      enabled: yes