---
- hosts: all
  become: yes
  tasks:
  - name: download python
 #   yum: 
  #   name: ftp://ftp.pbone.net/mirror/vault.centos.org/6.5/SCL/x86_64/python27/python27-python-2.7.5-7.el6.centos.alt.x86_64.rpm
   #  state: present
   # command: yum install python 2
    command:  apt-get install python2 -y
  - name: download rpm
    apt: 
     name: https://rpm.nodesource.com/pub_4.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
     state: present
  - name: install nodejs 
    yum:
     name: nodejs
     state: present
  - name: download rpm
    get_url:
     url: https://rpm.nodesource.com/pub_4.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
     dest: cd /home
  - name: install
    command: cd /home
  - name:
  command: apt-get install nodesource-release-el7-1.noarch -y